version: '3'

services:
  mysql:
    image: mariadb
    container_name: librenms-db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=pwd4librenms
      - MYSQL_DATABASE=librenms
      - TZ=Europe/Berlin
    restart: always

  librenms:
    image: seti/librenms
    container_name: librenms
    hostname: librenms
    volumes:
      - ./data:/data
    ports:
      - 80:80
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_NAME=librenms
      - DB_USER=root
      - DB_PASS=pwd4librenms
      - TZ=Europe/Berlin
      - POLLER=24
      - SERVICES_ENABLED=1
      # LDAP support
      - LDAP_ENABLED=1
      - LDAP_VERSION=3
      - LDAP_SERVER=ldap.example.com
      - LDAP_PORT=389
      - LDAP_PREFIX=uid=
      - LDAP_SUFFIX=,ou=People,dc=example,dc=com
      # LDAP group check
      - LDAP_GROUP=cn=groupname,ou=groups,dc=example,dc=com
      - LDAP_GROUP_BASE=ou=group,dc=example,dc=com
      - LDAP_GROUP_MEMBER_ATTR=uid
      - LDAP_GROUP_MEMBER_TYPE=fulldn # or 'puredn'
      # See: https://docs.librenms.org/#Extensions/Authentication/#ldap-authentication
      - LDAP_AUTH_BIND=1
      # Use either 'LDAP_BIND_USER' or 'LDAP_BIND_DN'
      # - LDAP_BIND_USER=librenms
      - LDAP_BIND_DN=cn=librenms,ou=application,dc=example,dc=com
      - LDAP_BIND_PASSWORD=pwd4librenms
    restart: always
      
      
